from lithos.plotting.processing import (
    _box,
    _bar_histogram,
    _jitter,
    _jitteru,
    _line,
    _poly_hist,
    _summary,
    _summaryu,
    _violin,
    _kde,
    _percent,
    _ecdf,
    _count,
    _scatter,
    _aggline,
)

processing_funcs = {
    "box": _box,
    "bar_histogram": _bar_histogram,
    "jitter": _jitter,
    "jitteru": _jitteru,
    "line": _line,
    "poly_hist": _poly_hist,
    "summary": _summary,
    "summaryu": _summaryu,
    "violin": _violin,
    "kde": _kde,
    "percent": _percent,
    "ecdf": _ecdf,
    "count": _count,
    "scatter": _scatter,
    "aggline": _aggline,
}
